tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "osx-cross/avr"
tap "px4/px4"
tap "sanemat/font"
tap "tophat/bar"
brew "anyenv"
brew "readline"
brew "autoconf"
brew "automake"
brew "avr-gcc@7", link: true
brew "avrdude"
brew "awscli"
brew "glib"
brew "pkg-config"
brew "certbot"
brew "circleci"
brew "cmake"
brew "dfu-programmer"
brew "gnutls"
brew "gobject-introspection"
brew "x264"
brew "ffmpeg"
brew "gh"
brew "gnu-sed"
brew "graphviz"
brew "grep"
brew "hub"
brew "imagemagick"
brew "jq"
brew "mas"
brew "massren"
brew "mbedtls"
brew "protobuf"
brew "mysql"
brew "peco"
brew "plantuml"
brew "postgresql"
brew "qt"
brew "redis"
brew "swig"
brew "terraform"
brew "texinfo"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "zsh"
brew "heroku/brew/heroku"
brew "px4/px4/gcc-arm-none-eabi"
brew "sanemat/font/ricty"
brew "tophat/bar/yvm"
cask "alfred"
cask "appcleaner"
cask "aws-vpn-client"
cask "clipy"
cask "discord"
cask "docker"
cask "figma"
cask "google-cloud-sdk"
cask "google-drive"
cask "hyperswitch"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "kindle"
cask "menumeters"
cask "miro"
cask "monitorcontrol"
cask "obs"
cask "qlmarkdown"
cask "shiftit"
cask "slack"
cask "spotify"
cask "tableplus"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "CotEditor", id: 1024640650
mas "Display Menu", id: 549083868
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Skitch", id: 425955336
mas "TweetDeck", id: 485812721
